let box=document.querySelector(".box")
box.style.height="100px"
box.style.backgroundColor="black"
box.style.width="100px"
box.style.border="5px solid orangered"
var btn=document.getElementById("btn")
btn.innerHTML="Tamam"
btn.style.borderRadius="10px"
btn.style.marginTop="20px"
